version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/helm-cm-push
    binary: bin/helm-cm-push
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    goarm64:
      - v8.0
    # Exclude windows arm builds (marked as broken by GoReleaser)
    ignore:
      - goos: windows
        goarch: arm

archives:
  - id: default
    formats: ["binary"]

release:
  disable: true
