apiVersion: v1
type: cli/v1
name: "cm-push"
version: "0.11.3"
runtime: subprocess
sourceURL: "https://github.com/ActianCorp/helm-push"
config:
  longHelp: "Please see https://github.com/ActianCorp/helm-push for usage"
  shortHelp: "Push chart package to ChartMuseum"
runtimeConfig:
  platformCommand:
    - command: "$HELM_PLUGIN_DIR/bin/helm-cm-push"
  platformHooks:
    install:
      - command: if [ -f "${HELM_PLUGIN_DIR}/scripts/install_plugin.sh" ]; then
          "${HELM_PLUGIN_DIR}/scripts/install_plugin.sh"
          fi
    update:
      - command: if [ -f "${HELM_PLUGIN_DIR}/scripts/install_plugin.sh" ]; then
          "${HELM_PLUGIN_DIR}/scripts/install_plugin.sh"
          fi
